name: Deploying To Dev Server
on:
  push:
    branches: 
      - main
jobs:
  deploymonorepo:
    name: Deploy every application to the dev server
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the dev server
        run: |
          cd ~
          mkdir .ssh
          echo "${{secrets.SSH_SECRET_PRIVATE_KEY_DEV}}" > ~/.ssh/dev.pem
          ssh-keyscan -H ${{ secrets.SSH_DEV_HOST }} >> ~/.ssh/known_hosts
          chmod 400 ~/.ssh/dev.pem
          ssh -i ~/.ssh/dev.pem ubuntu@54.242.252.5
          cd deploymonorepo

