name: Deploying To Dev Server
on:
  push:
    branches:
      - main
jobs:
  deploymonorepo:
    name: Deploy every application to the dev server
    runs-on: ubuntu-latest
    
    setps:
      - name: SSH into the dev server
        run: echo "Hi dev server"