name: Deploying To Dev Server
on:
  push:
    branches: 
      - main
jobs:
  deploymonorepo:
    name: Deploy every application to the dev server
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the dev server
        run: |
          cd ~
          pwd
